### ISSUE TITLE
DeprecationWarning useNewUrlParser: true

### ISSUE THREAD

**Issue by YasharF** [winstonjs/winston-mongodb#136]
`(node:6887) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.` 

I am encountering this under both my own project and when just running the winston-mongodb tests in a git clone of this repo. (by the way the tests don't seem to be exiting, perhaps due to an unreleased resource https://github.com/mochajs/mocha/issues/3044#issuecomment-344504423 )

```
/mnt/c/temp/winston-mongodb$ npm test

> winston-mongodb@4.0.3 test /mnt/c/temp/winston-mongodb
> mocha test/*-test.js --exit



(node:6887) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
  winston-mongodb-helpers
    #prepareMetaData()
      ✓ should preserve Date instances
      ✓ should store Error objects
      ✓ should store extra fields for custom Error objects

  {db: url} transport (abstract-winston-tranport)
    .log()
      ✓ should be present
      ✓ (with no callback) should return true
      ✓ (with callback) should return true
    events
      ✓ should emit the "logged" event

  {db: url} on capped collection transport (abstract-winston-tranport)
    .log()
      ✓ should be present
      ✓ (with no callback) should return true
      ✓ (with callback) should return true (46ms)
    events
      ✓ should emit the "logged" event

  {db: client promise} transport (abstract-winston-tranport)
    .log()
      ✓ should be present
      ✓ (with no callback) should return true
      ✓ (with callback) should return true
    events
      ✓ should emit the "logged" event

  {db: mongoose client} transport (abstract-winston-tranport)
    .log()
      ✓ should be present
      ✓ (with no callback) should return true
      ✓ (with callback) should return true
    events
      ✓ should emit the "logged" event


  19 passing (528ms)

```

In case of my own project, I have also tried the following but it still gives the same deprecation warning:
```
const Winston = require('winston');
require('winston-mongodb');

const winston = Winston.createLogger({
  levels: Winston.config.syslog.levels,
  transports: [
    new Winston.transports.MongoDB({
      db: process.env.MONGODB_URI
    },
    {
      useNewUrlParser: true
    })
  ]
});
```

**Comment by MastroLindus** [comment]
i fixed it by passing in the option subparam:

new transports.MongoDB({ capped: true, db: mongoUrl, name: "logs", collection: "logs", options: { poolSize: 2, autoReconnect: true, useNewUrlParser: true } }),

**Comment by YasharF** [comment]
@MastroLindus if I am reading your posting correctly, the following is what you stated would work, but I just tried again and the problem persists.

Steps to reporduce:

1. create a blank folder
2. run `npm init`
3. run `npm install winston --save`
4. run `npm install winston-mongodb --save`
5. create a file named index.js with the following content
```
const Winston = require('winston');
require('winston-mongodb');

const winston = Winston.createLogger({
  levels: Winston.config.syslog.levels,
  transports: [
    new Winston.transports.MongoDB({
      capped: true,
      db: process.env.MONGODB_URI,
      name: 'logs',
      collection: 'logs',
      oprions: {
        poolSize: 2,
        autoReconnect: true,
        useNewUrlParser: true,
      },
    })
  ]
});
```
6. run `node index.js`
it produced:
```
$ node index.js
(node:1884) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
```

additional info:
```
$ node -v
v10.9.0
$ npm -v
6.2.0
$ cat package.json
{
  "name": "b",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "winston": "^3.0.0",
    "winston-mongodb": "^4.0.3"
  }
}
```

**Comment by MastroLindus** [comment]
you have a typo, " oprions: { " instead of "options : {"

**Comment by YasharF** [comment]
Yes!  Thank you!

```
const Winston = require('winston');
require('winston-mongodb');

const winston = Winston.createLogger({
  levels: Winston.config.syslog.levels,
  transports: [
    new Winston.transports.MongoDB({
      capped: true,
      db: 'mongodb://localhost:27017/test',
      name: 'logs',
      collection: 'logs',
      options: {
        poolSize: 2,
        autoReconnect: true,
        useNewUrlParser: true,
      },
    })
  ]
});
```

It worked!  Thank you, thank you!

Perhaps this could be documented somewhere in the readme or it could be part of the default options in the next major version release.

**Comment by Shagequi** [comment]
Hi,
you should close this issue YasharF ;)

Thank you !

**Comment by MastroLindus** [comment]
@Shagequi I would still argue that "useNewUrlParser: true," should become the default value (still overriddable by  the user)

**Comment by Shagequi** [comment]
@MastroLindus 
Hey,
I created a pull request here : https://github.com/winstonjs/winston-mongodb/pull/143

An issue is a problem,
A pull request is a Solution proposal ;)
