### ISSUE TITLE
Not working with typescript

### ISSUE THREAD

**Issue by xduseko** [winstonjs/winston-mongodb#152]
Has anyone successfully used this transport along with Winston 3.x and Typescript based project? Without using compiler option `skipLibCheck`?

I can not find a way. Typescript is checking broken .d.ts file even if I use plain javascript to define logger with transport.

```
node_modules/winston-mongodb/lib/winston-mongodb.d.ts:6:10 - error TS2305: Module '"C:/Users/odu/IdeaProjects/engramo-server/node_modules/winston/index"' has no exported member 'TransportInstance'.

6 import { TransportInstance, Transports, TransportOptions } from "winston";
           ~~~~~~~~~~~~~~~~~


node_modules/winston-mongodb/lib/winston-mongodb.d.ts:6:41 - error TS2305: Module '"C:/Users/odu/IdeaProjects/engramo-server/node_modules/winston/index"' has no exported member 'TransportOptions'.

6 import { TransportInstance, Transports, TransportOptions } from "winston";
                                          ~~~~~~~~~~~~~~~~
```

**Comment by yurijmikhalevich** [comment]
Hi @xduseko. This issue was fixed in v4.0.4. Can you please check that it works for you with this version, and if not, reopen the issue?

**Comment by xduseko** [comment]
Thanks, I will take a look.

**Comment by xduseko** [comment]
It's still not working.

![image](https://user-images.githubusercontent.com/9591957/54527079-17c27080-4979-11e9-9837-c255060e8061.png)

MongoDB is not properly exported into winston namespace. It's not event exported from "winston-mongodb" module.

![image](https://user-images.githubusercontent.com/9591957/54527235-91f2f500-4979-11e9-9c98-daae721b6aae.png)

- typescript@2.9.2
- winston@3.2.1
- winston-mongodb@5.0.0

**Comment by lonix1** [comment]
Still broken.

Repro:
````
import MongoTransport from "winston-mongodb";
const transport = new MongoTransport({                  <--- error here
  // ...options
});
````

error:
> Cannot use 'new' with an expression whose type lacks a call or construct signature

**Comment by MasterOdin** [comment]
Alternative syntax to above that:
```typescript
import { MongoDB } from 'winston-mongodb';

declare module 'winston-mongodb' {
  const MongoDB: MongoDBTransportInstance;
}

let a = new MongoDB({
  "db": "test"
});
```

**Comment by Dilshan97** [comment]
> There is still problem with imports.
> 
> ![image](https://user-images.githubusercontent.com/9591957/54527079-17c27080-4979-11e9-9837-c255060e8061.png)
> 
> MongoDB is not properly exported into winston namespace. It's not event exported from "winston-mongodb" module.
> 
> ![image](https://user-images.githubusercontent.com/9591957/54527235-91f2f500-4979-11e9-9c98-daae721b6aae.png)
> 
> However MongoDB transport can be used like this.
> 
> ```js
> import { createLogger } from "winston";
> import { MongoDBTransportInstance } from "winston-mongodb";
> 
> const { MongoDB }: { MongoDB: MongoDBTransportInstance } = require("winston-mongodb");
> 
> const transport = new MongoDB({
> 	//...
> });
> 
> const logger = createLogger({
> 	level: "debug",
> 	transports: [ transport ]
> });
> ```
> 
> * typescript@2.9.2
> * winston@3.2.1
> * winston-mongodb@5.0.0

this works for me. thanks. you save my time
